const { Router } = require("express");
const { listar, obtener, alertas, crear, actualizar, crearInspeccion, listarInspecciones } = require("./vehiculos.controller");
const { verifyToken } = require("../../middlewares/auth.middleware");
const router = Router();
router.use(verifyToken);
router.get("/alertas", alertas);
router.get("/", listar);
router.get("/:id", obtener);
router.post("/", crear);
router.put("/:id", actualizar);
router.post("/:id/inspeccion", crearInspeccion);
router.get("/:id/inspecciones", listarInspecciones);
module.exports = router;
