version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pesv_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pesv_db
    ports:
      - "5432:5432"
    volumes:
      - pesv_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pesv_pgdata:
