const { Router } = require("express");
const { listar, crear, actualizar, estadisticas } = require("./desplazamientos.controller");
const { verifyToken } = require("../../middlewares/auth.middleware");
const router = Router();
router.use(verifyToken);
router.get("/estadisticas", estadisticas);
router.get("/", listar);
router.post("/", crear);
router.put("/:id", actualizar);
module.exports = router;
